import unittest
from pathlib import Path
import re


class MiniAppFrontendContractTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.content = Path('miniapp/index.html').read_text(encoding='utf-8')


    def test_user_facing_copy_is_product_style(self):
        self.assertIn('<title>Мини-викторина</title>', self.content)
        self.assertIn('/> Лёгкие</label>', self.content)
        self.assertIn('/> Средние</label>', self.content)
        self.assertIn('/> Сложные</label>', self.content)
        self.assertNotIn('Экспериментальный режим /ui', self.content)
        self.assertNotIn('Mini App API недоступен', self.content)
        self.assertNotIn('URL-транспорта', self.content)
        self.assertNotIn('opt-in /ui', self.content)
        self.assertNotIn('sendData недоступен', self.content)
        self.assertNotIn('server state', self.content)

    def test_diagnostics_hidden_by_default(self):
        self.assertIn('id="api_diag" class="note" hidden', self.content)
        self.assertIn('if (!debugMode) {', self.content)

    def test_debug_mode_query_flag_supported(self):
        self.assertIn("getQueryParam('debug') === '1'", self.content)

    def test_completed_view_has_next_actions(self):
        self.assertIn("restart.textContent = 'Новая викторина'", self.content)
        self.assertIn("closeBtn.textContent = 'Закрыть Mini App'", self.content)
        self.assertNotIn('location.reload();', self.content)
        self.assertIn('function getSafeSetupUrl()', self.content)
        self.assertIn('new URL(ctx.setup_url, location.origin)', self.content)
        self.assertIn("setupUrl.pathname === '/'", self.content)
        self.assertIn("setSetupStatus('ready_for_submit')", self.content)
        self.assertNotIn("ctx.setup_url.includes('api_base_url=')", self.content)
        self.assertIn('const safeSetupUrl = getSafeSetupUrl();', self.content)
        self.assertIn('if (safeSetupUrl) {', self.content)
        self.assertIn("await apiFetch(`${apiBase}/miniapp/setup-options`", self.content)
        self.assertIn("if (apiBase && tg?.initData) {", self.content)
        self.assertIn("setupOptionsCache.categories = categories;", self.content)
        self.assertIn("ctx.categories = categories;", self.content)
        self.assertIn('Чтобы начать новую викторину, закройте Mini App и отправьте /ui заново.', self.content)

    def test_setup_prefers_api_and_no_close_on_api_path(self):
        self.assertIn("/miniapp/setup", self.content)
        self.assertIn("if (apiBase && tg?.initData) {", self.content)
        self.assertIn("setSetupStatus('api_attempted')", self.content)
        self.assertIn("setSetupStatus('api_success')", self.content)
        self.assertIn('form.hidden = true;', self.content)
        self.assertIn('setupWarning.hidden = true;', self.content)
        self.assertIn("setSetupStatus('api_failed'", self.content)
        self.assertIn("if (go.disabled || setupSubmitInFlight) return;", self.content)
        self.assertIn("setupSubmitInFlight = true;", self.content)
        self.assertIn("setupSubmitInFlight = false;", self.content)
        self.assertIn("return;\n        }\n        if (!tg?.sendData)", self.content)
        self.assertNotIn("tg.close();", self.content)

    def test_ui_mode_helpers_prevent_mixed_dom(self):
        self.assertIn('function showSetupMode(', self.content)
        self.assertIn('function showRunnerMode()', self.content)
        self.assertIn('function showCompletedMode()', self.content)
        self.assertIn('function clearRunnerView()', self.content)
        self.assertIn('showSetupMode();', self.content)
        self.assertIn('showRunnerMode();', self.content)
        self.assertIn('showCompletedMode();', self.content)

    def test_timeout_and_feedback_ui_contract(self):
        self.assertIn("AbortController", self.content)
        self.assertIn("Не удалось отправить ответ через API. Попробуйте снова.", self.content)
        self.assertIn("Сеть подвисла, пробую отправить ещё раз...", self.content)
        self.assertIn("Запуск не удался, повторная попытка...", self.content)
        self.assertIn("Не удалось начать викторину. Попробуйте ещё раз.", self.content)
        self.assertIn("feedback-correct", self.content)
        self.assertIn("feedback-wrong", self.content)
        self.assertIn("next.textContent = 'Далее'", self.content)
        self.assertIn("answer-selected", self.content)
        self.assertIn("answer-pending", self.content)
        self.assertIn("answer-disabled", self.content)
        self.assertIn("answer-correct", self.content)
        self.assertIn("answer-selected-wrong", self.content)
        self.assertIn("ol button {", self.content)
        self.assertIn("border-radius: 14px;", self.content)
        self.assertIn("border: 1px solid #d6dce8;", self.content)
        self.assertIn("ol button.answer-selected {", self.content)
        self.assertIn("ol button.answer-pending {", self.content)
        self.assertIn("ol button.answer-correct {", self.content)
        self.assertIn("ol button.answer-selected-wrong {", self.content)
        self.assertIn("ol button.answer-selected {\n        border: 2px solid", self.content)
        self.assertIn("ol button.answer-pending {\n        border: 2px solid", self.content)
        self.assertIn("ol button.answer-correct {\n        border: 2px solid", self.content)
        self.assertIn("ol button.answer-selected-wrong {\n        border: 2px solid", self.content)
        self.assertIn("ol button.answer-selected {\n        border: 2px solid #5f6778;\n        background: #f3f5fa;", self.content)
        self.assertIn("ol button.answer-pending {\n        border: 2px solid #3653a5;\n        background: #eef3ff;", self.content)
        self.assertIn("ol button.answer-correct {\n        border: 2px solid #0a7d24;\n        background: #edf9f1;", self.content)
        self.assertIn("ol button.answer-selected-wrong {\n        border: 2px solid #b00020;\n        background: #fff1f3;", self.content)
        self.assertNotIn(".answer-selected { outline:", self.content)
        self.assertNotIn(".answer-pending {\n        outline:", self.content)
        self.assertNotIn(".answer-correct {\n        outline:", self.content)
        self.assertNotIn(".answer-selected-wrong {\n        outline:", self.content)
        self.assertIn("ol button:disabled {", self.content)
        self.assertIn("-webkit-text-fill-color: #222;", self.content)
        self.assertNotIn("opacity: 0.65;", self.content)
        self.assertIn("statusEl.textContent = 'Проверяю ответ...';", self.content)
        self.assertIn("status.className = 'answer-status';", self.content)
        self.assertIn("statusEl.classList.add('pending');", self.content)
        self.assertIn("Ваш ответ:", self.content)
        self.assertIn("Правильный ответ:", self.content)
        self.assertNotIn("Правильный ответ: ?.", self.content)
        self.assertIn("Отправляю ответ...", self.content)
        self.assertIn("Проверяю, был ли ответ принят...", self.content)
        self.assertIn("Повторная отправка ответа...", self.content)
        self.assertIn("Ответ принят.", self.content)
        self.assertIn("Ответ принят, состояние обновлено.", self.content)
        self.assertIn("Ответ уже был принят, состояние обновлено.", self.content)
        self.assertIn("Не удалось обновить интерфейс после ответа. Попробуйте снова.", self.content)
        self.assertIn("feedback-line", self.content)
        self.assertIn("next.className = 'answer-next';", self.content)


    def test_incomplete_feedback_resync_guard(self):
        self.assertIn('function hasCompleteFeedback(feedback)', self.content)
        self.assertIn("function getResyncedFeedbackForSubmission(stateData, submittedQuestionId, selectedOptionIndex)", self.content)
        self.assertIn("const feedback = stateData?.recent_answer_feedback;", self.content)
        self.assertIn("if (hasCompleteFeedback(answerJson.feedback))", self.content)
        self.assertIn("answerJson.submission_status === 'duplicate'", self.content)
        self.assertIn("answerJson.submission_status === 'stale_question'", self.content)
        self.assertIn("answerJson.submission_status === 'resynced_with_feedback'", self.content)
        self.assertIn("renderRunnerState(answerJson.runner_state, { preferLaunchCompact: false });", self.content)

    def test_no_automatic_send_data_after_api_failures(self):
        self.assertIn("apiDiagState.answerPhase = 'retry_exhausted';", self.content)
        self.assertNotIn("setSetupStatus('explicit_fallback_sendData');", self.content)
        self.assertIn("if (answerSubmitInFlight) return;", self.content)
        self.assertNotIn("'X-Miniapp-Request-Id': requestId", self.content)
        self.assertIn("if (!tg?.sendData)", self.content)

    def test_simple_body_transport_contract(self):
        self.assertIn("headers: { 'Content-Type': 'text/plain;charset=UTF-8' }", self.content)
        self.assertIn("init_data: initData", self.content)
        self.assertIn("request_id: attemptRequestId", self.content)
        self.assertIn("apiDiagState.answerTransport = 'simple_body';", self.content)
        self.assertIn("apiDiagState.setupTransport = 'simple_body';", self.content)
        self.assertNotIn("'X-Miniapp-Request-Id': requestId", self.content)

    def test_debug_diagnostics_include_safe_request_phases(self):
        self.assertIn("function buildMiniappRequestId()", self.content)
        self.assertIn("function firstSuccessfulOrAllFailed(candidateFactories)", self.content)
        self.assertIn("function apiFetchWithRetry(", self.content)
        self.assertNotIn("Promise.race([attemptPromise, hedgePromise])", self.content)
        self.assertIn("apiDiagState.answerPhase = 'preparing';", self.content)
        self.assertIn("const ANSWER_API_TIMEOUT_MS = 8000;", self.content)
        self.assertIn("const ANSWER_HEDGE_DELAY_MS = 3000;", self.content)
        self.assertIn("apiDiagState.answerPhase = 'retry_scheduled';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'answer_hedge_timer_started';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'answer_hedge_state_resync_attempted';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'answer_hedge_state_resync_success';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'answer_hedge_state_resync_no_change';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'answer_hedge_retry_started';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'answer_late_result_ignored';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'pre_retry_state_resync_attempted';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'pre_retry_state_resync_success';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'pre_retry_state_resync_no_change';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'pre_retry_state_resync_failed';", self.content)
        self.assertIn("'retry_started'", self.content)
        self.assertIn("runnerState.textContent = 'Повторная отправка ответа...';", self.content)
        self.assertIn("runnerState.textContent = 'Сеть подвисла, пробую отправить ещё раз...';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'retry_exhausted';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'state_resync_attempted';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'state_resync_success';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'state_resync_failed';", self.content)
        self.assertIn("apiDiagState.answerPhase = 'ui_render_failed';", self.content)
        self.assertNotIn("Authorization: `tma ${initData}` +", self.content)
        self.assertIn("database_busy_retry", self.content)
        self.assertIn("status === 503", self.content)
        self.assertIn("status === 429", self.content)
        self.assertIn("Math.floor(Math.random() * 500)", self.content)
        self.assertIn("function getRetryDelayMs(baseMs)", self.content)
        self.assertIn("await waitMs(getRetryDelayMs(backoffMs[attempt - 1] || 1000));", self.content)
        self.assertIn("function pushDiagPhase(track, phase, startedAt, extras = {})", self.content)
        self.assertIn("pushDiagPhase('answer', 'request_scheduled'", self.content)
        self.assertIn("pushDiagPhase('answer', 'response_headers_received'", self.content)
        self.assertIn("pushDiagPhase('answer', 'response_body_parsed'", self.content)
        self.assertIn("pushDiagPhase('answer', 'state_update_started'", self.content)
        self.assertIn("pushDiagPhase('answer', 'state_update_applied'", self.content)
        self.assertIn("pushDiagPhase('answer', 'ui_render_mark'", self.content)
        self.assertIn("pushDiagPhase('setup', 'request_scheduled'", self.content)
        self.assertIn("pushDiagPhase('setup', 'response_headers_received'", self.content)
        self.assertIn("pushDiagPhase('setup', 'response_body_parsed'", self.content)
        self.assertIn("pushDiagPhase('setup', 'state_update_started'", self.content)
        self.assertIn("pushDiagPhase('setup', 'state_update_applied'", self.content)
        self.assertIn("pushDiagPhase('setup', 'ui_render_mark'", self.content)
        self.assertIn("answer_transport:", self.content)
        self.assertIn("setup_transport:", self.content)


    def test_docs_numbered_h2_headings_have_unique_numbers(self):
        docs = Path('docs/miniapp-deployment-qa.md').read_text(encoding='utf-8')
        numbers = re.findall(r'^## (\d+)\)', docs, flags=re.MULTILINE)
        self.assertTrue(numbers, 'Expected numbered ## headings in docs/miniapp-deployment-qa.md')
        duplicates = sorted({n for n in numbers if numbers.count(n) > 1}, key=int)
        self.assertEqual(duplicates, [], f'Duplicate numbered ## headings found: {duplicates}')

    def test_debug_diagnostics_do_not_render_secrets(self):
        self.assertNotIn("tg.initData", " ".join(line for line in self.content.splitlines() if "apiDiag.textContent" in line or "answer_phases" in line or "setup_phases" in line))
        self.assertNotIn("Authorization", " ".join(line for line in self.content.splitlines() if "apiDiag.textContent" in line))

    def test_state_advance_helper_contract(self):
        self.assertIn('function didRunnerStateAdvanceForAnswer(submittedSessionId, submittedQuestionId, runnerState)', self.content)
        self.assertIn('const nestedSessionId = Number(runnerState.session?.session_id);', self.content)
        self.assertIn('const resolvedSessionId = Number.isInteger(nestedSessionId) ? nestedSessionId : (', self.content)
        self.assertIn('if (Number.isInteger(resolvedSessionId) && resolvedSessionId !== Number(submittedSessionId)) return false;', self.content)
        self.assertIn("stateName === 'completed'", self.content)
        self.assertIn("statusName === 'no_current_question'", self.content)
        self.assertIn('currentQuestionId !== Number(submittedQuestionId);', self.content)

    def test_setup_mode_hydration_is_guarded(self):
        self.assertIn("const hydrateOnSetup = ctx?.hydrate_on_setup === true;", self.content)
        self.assertIn("if (apiBase && tg?.initData && (!setupMode || hydrateOnSetup)) {", self.content)
        self.assertIn("await apiFetch(`${apiBase}/miniapp/state`", self.content)


if __name__ == '__main__':
    unittest.main()
