import { expect, test, type Page } from '@playwright/test'

const backend = 'http://127.0.0.1:8085'
const email = 'owner@example.test', password = 'A synthetic browser passphrase'

test('reading catalog preserves separate lists, lost save and reload', async ({ page }, testInfo) => {
  await fresh(page)
  await page.getByRole('button', { name: 'Литература', exact: true }).click()
  await expect(page.getByText('Работ: 114')).toBeVisible()
  await page.getByLabel('Тема литературы').selectOption('fiziologiya_cheloveka')
  await expect(page.getByText('Работ: 15')).toBeVisible()
  await page.locator('.literature-title').first().click()
  const title = await page.locator('.literature-detail h2').innerText()
  const first = await page.getByLabel('Учебный список').inputValue()
  await page.getByLabel('Статус чтения').selectOption('in_progress')
  await page.getByLabel('Прочитано, %').fill('37')
  await page.route('**/web/literature/progress', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('button', { name: 'Сохранить чтение' }).click()
  await expect(page.getByLabel('Статус чтения')).toBeDisabled()
  await page.getByRole('button', { name: 'Обновить каталог и прогресс' }).click()
  await expect(page.getByLabel('Прочитано, %')).toHaveValue('37')
  await page.getByLabel('Учебный список').selectOption({ index: 1 })
  await expect(page.getByLabel('Статус чтения')).toHaveValue('not_started')
  await page.getByLabel('Статус чтения').selectOption('read')
  await page.getByRole('button', { name: 'Сохранить чтение' }).click()
  await expect(page.getByText('Прогресс чтения сохранён.')).toBeVisible()
  await page.getByLabel('Учебный список').selectOption(first)
  await expect(page.getByLabel('Прочитано, %')).toHaveValue('37')
  await page.getByText('Источник и библиографическая запись').click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-reading.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.reload()
  await page.getByRole('button', { name: 'Литература', exact: true }).click()
  await page.getByRole('button', { name: title, exact: true }).click()
  await page.getByLabel('Учебный список').selectOption(first)
  await expect(page.getByLabel('Прочитано, %')).toHaveValue('37')
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
})

test('reading empty and failed catalog loads are recoverable', async ({ page }) => {
  await fresh(page)
  await page.route('**/web/literature/catalog', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ ok: false, error: 'database_unavailable' }) }), { times: 1 })
  await page.getByRole('button', { name: 'Литература', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Сервер занят')
  await page.route('**/web/literature/catalog', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ ok: true, works: [], topics: [] }) }), { times: 1 })
  await page.getByRole('button', { name: 'Литература', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Список пока пуст' })).toBeVisible()
  await page.getByRole('button', { name: 'Обновить каталог и прогресс' }).click()
  await expect(page.getByText('Работ: 114')).toBeVisible()
})

async function syntheticPost(page: Page, action: string, payload: unknown) {
  const account = await (await page.request.get('/web/auth/me')).json()
  const response = await page.request.post(`/web/${action}`, { data: payload, headers: { Origin: 'http://127.0.0.1:4173', 'X-CSRF-Token': account.csrf_token } })
  expect(response.ok()).toBeTruthy()
  return response.json()
}

test('glossary survives lost setup, repeated answer, reload and completion', async ({ page }, testInfo) => {
  await fresh(page)
  await page.getByRole('button', { name: 'Глоссарий', exact: true }).click()
  await page.getByLabel('Тема глоссария').selectOption('obschaya_psihologiya')
  await page.route('**/web/glossary/setup', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('button', { name: 'Начать тест по терминам' }).click()
  await page.getByRole('button', { name: 'Восстановить глоссарий' }).click()
  const before = await (await page.request.get('/web/glossary/state')).json()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-glossary.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.route('**/web/glossary/answer', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('radio').first().check()
  await page.getByRole('button', { name: 'Проверить определение' }).click()
  await expect(page.getByRole('radio').last()).toBeDisabled()
  await page.getByRole('button', { name: 'Повторить тот же ответ' }).click()
  await expect(page.getByText('Ответ сохранён · 1 из 5')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Глоссарий', exact: true }).click()
  await expect(page.getByText('Ответ сохранён · 1 из 5')).toBeVisible()
  expect((await (await page.request.get('/web/glossary/state')).json()).glossary_state.current_question).toEqual(before.glossary_state.current_question)
  for (let step = 2; step <= 5; step++) {
    await page.getByRole('button', { name: 'Следующий термин' }).click()
    await page.getByRole('radio').first().check()
    await page.getByRole('button', { name: 'Проверить определение' }).click()
    await expect(page.getByText(`Ответ сохранён · ${step} из 5`)).toBeVisible()
  }
  await page.getByRole('button', { name: 'Показать результат' }).click()
  await expect(page.getByRole('heading', { name: 'Тест по терминам завершён' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Глоссарий', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Тест по терминам завершён' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
})

test('glossary replacement needs confirmation and topic reset preserves another quiz', async ({ page }) => {
  await fresh(page)
  const quiz = await syntheticPost(page, 'quiz/setup', { quiz_mode: 'all', category_ids: [], question_count: null, difficulty: 'any' })
  await page.getByRole('button', { name: 'Глоссарий', exact: true }).click()
  await page.getByLabel('Тема глоссария').selectOption('obschaya_psihologiya')
  await page.getByRole('button', { name: 'Начать тест по терминам' }).click()
  await page.getByRole('button', { name: '← К темам глоссария' }).click()
  await expect(page.getByRole('button', { name: 'Начать тест по терминам' })).toBeDisabled()
  await page.getByRole('button', { name: 'К сохранённому тесту' }).click()
  await page.getByRole('radio').first().check()
  await page.getByRole('button', { name: 'Проверить определение' }).click()
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await page.getByRole('button', { name: 'Сбросить учебный прогресс' }).click()
  await page.getByRole('combobox').selectOption('topic:Общая психология')
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  expect((await (await page.request.get('/web/glossary/state')).json()).glossary_state.state).toBe('feedback')
  await page.getByRole('button', { name: 'Сбросить учебный прогресс' }).click()
  await page.getByRole('combobox').selectOption('topic:Общая психология')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Подтвердить сброс' }).click()
  await expect(page.getByText('Учебный прогресс сброшен.')).toBeVisible()
  expect((await (await page.request.get('/web/quiz/state')).json()).runner_state.session.session_id).toBe(quiz.runner_state.session.session_id)
  await page.getByRole('button', { name: 'Глоссарий', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Начать тест по терминам' })).toBeEnabled()
})

test('reset previews, cancels, clears one historical topic then all, and survives reload', async ({ page }, testInfo) => {
  await fresh(page)
  let quiz = await syntheticPost(page, 'quiz/setup', { quiz_mode: 'all', category_ids: [], question_count: null, difficulty: 'any' })
  while (quiz.runner_state.state === 'in_progress') {
    const question = quiz.runner_state.current_question
    quiz = await syntheticPost(page, 'quiz/answer', { session_id: question.session_id, question_id: question.question_id, selected_option_index: 0 })
  }
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await expect(page.getByText('7 из 7 ответов', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить учебный прогресс' }).click()
  await expect(page.getByRole('button', { name: 'Подтвердить сброс' })).toBeDisabled()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await expect(page.getByText('7 из 7 ответов', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить учебный прогресс' }).click()
  await page.getByRole('combobox').selectOption('topic:Основы психологии')
  await expect(page.getByText(/Ответы других тем/)).toBeVisible()
  await page.getByRole('checkbox').check()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-reset.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Подтвердить сброс' }).click()
  await expect(page.getByText('Учебный прогресс сброшен.')).toBeVisible()
  await expect(page.getByText('2 из 2 ответов', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await expect(page.getByText('2 из 2 ответов', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить учебный прогресс' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Подтвердить сброс' }).click()
  await expect(page.getByText('История начинается с первого ответа')).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить учебный прогресс' }).click()
  await expect(page.getByText('В выбранном разделе нет попыток для сброса.')).toBeVisible()
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
})

test('stale reset and lost response require a new preview without deleting new learning', async ({ page }) => {
  await fresh(page)
  await start(page)
  await page.getByRole('radio', { name: 'Только скорость' }).check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await page.getByRole('button', { name: 'Сбросить учебный прогресс' }).click()
  await page.getByRole('checkbox').check()
  const state = await (await page.request.get('/web/quiz/state')).json()
  const question = state.runner_state.current_question
  await syntheticPost(page, 'quiz/answer', { session_id: question.session_id, question_id: question.question_id, selected_option_index: 0 })
  await page.getByRole('button', { name: 'Подтвердить сброс' }).click()
  await expect(page.getByRole('alert')).toContainText('Прогресс изменился')
  await expect(page.getByRole('button', { name: 'Подтвердить сброс' })).toBeDisabled()
  await page.getByRole('button', { name: 'Обновить просмотр' }).click()
  await page.getByRole('checkbox').check()
  await page.route('**/web/progress/reset-confirm', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('button', { name: 'Подтвердить сброс' }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await syntheticPost(page, 'quiz/setup', { quiz_mode: 'all', category_ids: [], question_count: 5, difficulty: 'any' })
  await page.getByRole('button', { name: 'Обновить просмотр' }).click()
  await expect(page.getByRole('checkbox')).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Подтвердить сброс' })).toBeDisabled()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await expect(page.getByText('Всего попыток: 1')).toBeVisible()
})

test.beforeEach(async ({ request }) => {
  expect((await request.post(backend + '/__test/reset', { data: { seed: true } })).ok()).toBeTruthy()
})

async function login(page: Page, pass = password) {
  await page.goto('/')
  await page.getByLabel('Электронная почта').fill(email)
  await page.getByLabel('Пароль', { exact: true }).fill(pass)
  const response = page.waitForResponse('**/web/auth/login')
  await page.getByRole('button', { name: 'Войти в пространство' }).click()
  await response
}

async function fresh(page: Page) {
  await login(page)
  await page.getByRole('button', { name: 'Создать новый прогресс' }).click()
  await page.getByRole('button', { name: 'Начать с чистого листа' }).click()
  await expect(page.getByRole('heading', { name: 'Что изучим сегодня?' })).toBeVisible()
}

async function start(page: Page) {
  await page.getByRole('radio', { name: 'Основы психологии' }).check()
  await page.getByRole('button', { name: '5', exact: true }).click()
  await page.getByRole('button', { name: 'Начать квиз', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Осмысленное повторение' })).toBeVisible()
}

test('personal progress, historical mistakes and retry-safe training share the quiz state', async ({ page }, testInfo) => {
  await fresh(page)
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await expect(page.getByText('История начинается с первого ответа')).toBeVisible()
  await page.getByRole('button', { name: 'Мои ошибки', exact: true }).click()
  await expect(page.getByText('Сейчас нет вопросов для тренировки')).toBeVisible()
  await page.getByRole('button', { name: 'Квиз по психологии' }).click()
  await start(page)
  await page.getByRole('radio', { name: 'Только скорость' }).check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await page.getByRole('button', { name: 'Мои ошибки', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Для тренировки: 1' })).toBeVisible()
  await page.getByText('Разобрать ответ', { exact: true }).click()
  await expect(page.getByText('Только скорость', { exact: true })).toBeVisible()
  await expect(page.getByText('Повторение помогает', { exact: false })).toBeVisible()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-errors.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  const old = await (await page.request.get('/web/quiz/state')).json()
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  expect((await (await page.request.get('/web/quiz/state')).json()).runner_state.session).toEqual(old.runner_state.session)
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await page.route('**/web/progress/train', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('button', { name: 'Заменить квиз и начать' }).click()
  await page.getByRole('button', { name: 'Восстановить квиз' }).click()
  await expect(page.getByText('Вопрос 1 из 1')).toBeVisible()
  await page.getByRole('radio', { name: 'Осмысленное повторение' }).check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await page.getByRole('button', { name: 'Мои ошибки', exact: true }).click()
  await expect(page.getByText('Сейчас нет вопросов для тренировки')).toBeVisible()
  await expect(page.getByText('Разобрать ответ', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await expect(page.getByText('1 из 2 ответов')).toBeVisible()
  await expect(page.getByText('Прервана', { exact: true })).toBeVisible()
  await expect(page.getByText('Завершена', { exact: true })).toBeVisible()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-progress.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: `Открыть попытку ${old.runner_state.session.session_id}` }).click()
  await expect(page.getByRole('heading', { name: 'Разбор попытки' })).toBeVisible()
  await expect(page.getByText('Ответ был неверным')).toBeVisible()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-history.png`, fullPage: true })
  await page.reload()
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await expect(page.getByText('1 из 2 ответов')).toBeVisible()
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
})

test('progress network failure can be retried and expiry removes personal data', async ({ page }) => {
  await fresh(page)
  await page.route('**/web/progress/overview', route => route.abort('failed'), { times: 1 })
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Нет подтверждения')
  await page.getByRole('button', { name: 'Мой прогресс', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Мой прогресс' })).toBeVisible()
  await page.route('**/web/progress/errors', route => route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ ok: false, error: 'unauthorized' }) }), { times: 1 })
  await page.getByRole('button', { name: 'Мои ошибки', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Войти в пространство' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Мой прогресс' })).toHaveCount(0)
})

test('independent quiz saves answers, explains mistakes, resumes and completes', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Войти в пространство' })).toBeVisible()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-login.png`, fullPage: true })
  await fresh(page)
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-setup.png`, fullPage: true })
  await start(page)
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-question.png`, fullPage: true })
  await page.getByRole('radio', { name: 'Только скорость' }).check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await expect(page.getByText('Разберём этот ответ')).toBeVisible()
  await expect(page.getByText('Повторение помогает', { exact: false })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Только скорость', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Следующий вопрос' }).click()
  for (let i = 0; i < 4; i++) {
    await page.getByRole('radio', { name: 'Осмысленное повторение' }).check()
    await page.getByRole('button', { name: 'Проверить ответ' }).click()
    await page.getByRole('button', { name: i === 3 ? 'Посмотреть результат' : 'Следующий вопрос' }).click()
  }
  await expect(page.getByRole('heading', { name: '80% верных ответов' })).toBeVisible()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-result.png`, fullPage: true })
  await page.reload()
  await expect(page.getByRole('heading', { name: '80% верных ответов' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Мой аккаунт' }).click()
  await expect(page.getByRole('button', { name: 'Установить приложение' }).filter({ visible: true })).toBeVisible()
  await page.getByRole('button', { name: 'Выйти', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Войти в пространство' })).toBeVisible()
  expect((await page.request.get('/web/quiz/state')).status()).toBe(401)
})

test('lost reply after commit retries the same answer once and restores uncertain setup', async ({ page }) => {
  await fresh(page)
  await page.route('**/web/quiz/setup', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('radio', { name: 'Основы психологии' }).check()
  await page.getByRole('button', { name: '5', exact: true }).click()
  await page.getByRole('button', { name: 'Начать квиз', exact: true }).click()
  await page.getByRole('button', { name: 'Восстановить квиз' }).click()
  await page.route('**/web/quiz/answer', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('radio', { name: 'Осмысленное повторение' }).check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await expect(page.getByRole('radio').first()).toBeDisabled()
  await page.getByRole('button', { name: 'Повторить отправку' }).click()
  await expect(page.getByText('Ответ сохранён', { exact: true })).toBeVisible()
  const state = await (await page.request.get('/web/quiz/state')).json()
  expect(state.runner_state.progress.answered_count).toBe(1)
  await page.getByRole('button', { name: 'Следующий вопрос' }).click()
  await expect(page.getByText('Вопрос 2 из 5')).toBeVisible()
})

test('email verification and recovery use fragments, revoke session and reject old password', async ({ page, request }) => {
  await request.post(backend + '/__test/reset', { data: { seed: false } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Первый вход' }).click()
  await page.getByLabel('Электронная почта').fill(email)
  await page.getByRole('button', { name: 'Получить письмо' }).click()
  await expect(page.getByRole('status')).toContainText('письмо уже отправлено')
  const mail = await (await request.get(backend + '/__test/mail')).json()
  await page.goto('/#verify=' + mail.messages.at(-1).token)
  await expect(page.getByRole('heading', { name: 'Создайте свой пароль' })).toBeVisible()
  expect(page.url()).toBe('http://127.0.0.1:4173/')
  await page.getByLabel('Новый пароль').fill(password)
  await page.getByRole('button', { name: 'Сохранить пароль' }).click()
  await expect(page.getByRole('status')).toContainText('Пароль сохранён')
  await login(page)
  const cookies = await page.context().cookies()
  expect(cookies.find(c => c.name === 'psychology_dev_session')?.httpOnly).toBeTruthy()
  await request.post('http://127.0.0.1:4173/web/auth/recover', { data: { email }, headers: { Origin: 'http://127.0.0.1:4173' } })
  const recovery = await (await request.get(backend + '/__test/mail')).json()
  await page.goto('/#recover=' + recovery.messages.at(-1).token)
  await page.getByLabel('Новый пароль').fill(password + ' changed')
  await page.getByRole('button', { name: 'Сохранить пароль' }).click()
  await expect(page.getByRole('status')).toContainText('Пароль сохранён')
  expect((await page.request.get('/web/auth/me')).status()).toBe(401)
  await login(page)
  await expect(page.getByRole('alert')).toContainText('Не удалось войти')
  await login(page, password + ' changed')
  await expect(page.getByText('Ваш прогресс — с вами')).toBeVisible()
})

test('linking requires Telegram proof then explicit confirmation in the browser', async ({ page, request }) => {
  await login(page)
  await page.getByRole('button', { name: 'Получить код' }).click()
  const command = await page.getByRole('textbox', { name: 'Команда для бота' }).inputValue()
  await request.post(backend + '/__test/telegram-confirm', { data: { code: command.replace('/link ', '') } })
  await page.getByRole('button', { name: 'Я подтвердил в Telegram' }).click()
  await expect(page.getByText('Учебный аккаунт', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Подключить этот прогресс' }).click()
  await expect(page.getByRole('heading', { name: 'Что изучим сегодня?' })).toBeVisible()
  await page.getByRole('button', { name: 'Мой аккаунт' }).click()
  await expect(page.getByText('Прогресс связан с вашим Telegram-аккаунтом.')).toBeVisible()
})

test('installable assets exist and offline worker contains no private data', async ({ page, context }) => {
  await fresh(page)
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await page.reload()
  const manifest = await (await page.request.get('/manifest.webmanifest')).json()
  expect(manifest.display).toBe('standalone')
  for (const icon of manifest.icons) expect((await page.request.get(icon.src)).headers()['content-type']).toContain('image/png')
  const cached = await page.evaluate(async () => Promise.all((await caches.keys()).map(async name => ({ name, urls: (await (await caches.open(name)).keys()).map(r => r.url) }))))
  expect(cached.length).toBeGreaterThan(0)
  expect(cached.flatMap(c => c.urls)).toEqual(['http://127.0.0.1:4173/offline.html'])
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Продолжим, когда появится связь' })).toBeVisible()
  await expect(page.getByText(email)).toHaveCount(0)
  await context.setOffline(false)
  await page.getByRole('link', { name: 'Попробовать подключиться' }).click()
  await expect(page.getByRole('heading', { name: 'Что изучим сегодня?' })).toBeVisible()
})

test('keyboard can submit login and reach the main-content skip link', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Электронная почта').focus()
  await page.keyboard.type(email)
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Пароль', { exact: true })).toBeFocused()
  await page.keyboard.type(password)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Ваш прогресс — с вами' })).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Перейти к содержимому' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()
})
