import { expect, test, type Page } from '@playwright/test'

const backend = 'http://127.0.0.1:8085'
const email = 'owner@example.test', password = 'A synthetic browser passphrase'

test.beforeEach(async ({ request }) => {
  expect((await request.post(backend + '/__test/reset', { data: { seed: true } })).ok()).toBeTruthy()
})

async function login(page: Page, pass = password) {
  await page.goto('/')
  await page.getByLabel('Электронная почта').fill(email)
  await page.getByLabel('Пароль', { exact: true }).fill(pass)
  const response = page.waitForResponse('**/web/auth/login')
  await page.getByRole('button', { name: 'Войти в пространство' }).click()
  await response
}

async function fresh(page: Page) {
  await login(page)
  await page.getByRole('button', { name: 'Создать новый прогресс' }).click()
  await page.getByRole('button', { name: 'Начать с чистого листа' }).click()
  await expect(page.getByRole('heading', { name: 'Что изучим сегодня?' })).toBeVisible()
}

async function start(page: Page) {
  await page.getByRole('radio', { name: 'Основы психологии' }).check()
  await page.getByRole('button', { name: '5', exact: true }).click()
  await page.getByRole('button', { name: 'Начать квиз', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Осмысленное повторение' })).toBeVisible()
}

test('independent quiz saves answers, explains mistakes, resumes and completes', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Войти в пространство' })).toBeVisible()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-login.png`, fullPage: true })
  await fresh(page)
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-setup.png`, fullPage: true })
  await start(page)
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-question.png`, fullPage: true })
  await page.getByRole('radio', { name: 'Только скорость' }).check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await expect(page.getByText('Разберём этот ответ')).toBeVisible()
  await expect(page.getByText('Повторение помогает', { exact: false })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Только скорость', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Следующий вопрос' }).click()
  for (let i = 0; i < 4; i++) {
    await page.getByRole('radio', { name: 'Осмысленное повторение' }).check()
    await page.getByRole('button', { name: 'Проверить ответ' }).click()
    await page.getByRole('button', { name: i === 3 ? 'Посмотреть результат' : 'Следующий вопрос' }).click()
  }
  await expect(page.getByRole('heading', { name: '80% верных ответов' })).toBeVisible()
  await page.screenshot({ path: `test-results/visual-${testInfo.project.name}-result.png`, fullPage: true })
  await page.reload()
  await expect(page.getByRole('heading', { name: '80% верных ответов' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Мой аккаунт' }).click()
  await expect(page.getByRole('button', { name: 'Установить приложение' }).filter({ visible: true })).toBeVisible()
  await page.getByRole('button', { name: 'Выйти', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Войти в пространство' })).toBeVisible()
  expect((await page.request.get('/web/quiz/state')).status()).toBe(401)
})

test('lost reply after commit retries the same answer once and restores uncertain setup', async ({ page }) => {
  await fresh(page)
  await page.route('**/web/quiz/setup', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('radio', { name: 'Основы психологии' }).check()
  await page.getByRole('button', { name: '5', exact: true }).click()
  await page.getByRole('button', { name: 'Начать квиз', exact: true }).click()
  await page.getByRole('button', { name: 'Восстановить квиз' }).click()
  await page.route('**/web/quiz/answer', async route => { await route.fetch(); await route.abort('failed') }, { times: 1 })
  await page.getByRole('radio', { name: 'Осмысленное повторение' }).check()
  await page.getByRole('button', { name: 'Проверить ответ' }).click()
  await expect(page.getByRole('radio').first()).toBeDisabled()
  await page.getByRole('button', { name: 'Повторить отправку' }).click()
  await expect(page.getByText('Ответ сохранён', { exact: true })).toBeVisible()
  const state = await (await page.request.get('/web/quiz/state')).json()
  expect(state.runner_state.progress.answered_count).toBe(1)
  await page.getByRole('button', { name: 'Следующий вопрос' }).click()
  await expect(page.getByText('Вопрос 2 из 5')).toBeVisible()
})

test('email verification and recovery use fragments, revoke session and reject old password', async ({ page, request }) => {
  await request.post(backend + '/__test/reset', { data: { seed: false } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Первый вход' }).click()
  await page.getByLabel('Электронная почта').fill(email)
  await page.getByRole('button', { name: 'Получить письмо' }).click()
  await expect(page.getByRole('status')).toContainText('письмо уже отправлено')
  const mail = await (await request.get(backend + '/__test/mail')).json()
  await page.goto('/#verify=' + mail.messages.at(-1).token)
  await expect(page.getByRole('heading', { name: 'Создайте свой пароль' })).toBeVisible()
  expect(page.url()).toBe('http://127.0.0.1:4173/')
  await page.getByLabel('Новый пароль').fill(password)
  await page.getByRole('button', { name: 'Сохранить пароль' }).click()
  await expect(page.getByRole('status')).toContainText('Пароль сохранён')
  await login(page)
  const cookies = await page.context().cookies()
  expect(cookies.find(c => c.name === 'psychology_dev_session')?.httpOnly).toBeTruthy()
  await request.post('http://127.0.0.1:4173/web/auth/recover', { data: { email }, headers: { Origin: 'http://127.0.0.1:4173' } })
  const recovery = await (await request.get(backend + '/__test/mail')).json()
  await page.goto('/#recover=' + recovery.messages.at(-1).token)
  await page.getByLabel('Новый пароль').fill(password + ' changed')
  await page.getByRole('button', { name: 'Сохранить пароль' }).click()
  await expect(page.getByRole('status')).toContainText('Пароль сохранён')
  expect((await page.request.get('/web/auth/me')).status()).toBe(401)
  await login(page)
  await expect(page.getByRole('alert')).toContainText('Не удалось войти')
  await login(page, password + ' changed')
  await expect(page.getByText('Ваш прогресс — с вами')).toBeVisible()
})

test('linking requires Telegram proof then explicit confirmation in the browser', async ({ page, request }) => {
  await login(page)
  await page.getByRole('button', { name: 'Получить код' }).click()
  const command = await page.getByRole('textbox', { name: 'Команда для бота' }).inputValue()
  await request.post(backend + '/__test/telegram-confirm', { data: { code: command.replace('/link ', '') } })
  await page.getByRole('button', { name: 'Я подтвердил в Telegram' }).click()
  await expect(page.getByText('Учебный аккаунт', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Подключить этот прогресс' }).click()
  await expect(page.getByRole('heading', { name: 'Что изучим сегодня?' })).toBeVisible()
  await page.getByRole('button', { name: 'Мой аккаунт' }).click()
  await expect(page.getByText('Прогресс связан с вашим Telegram-аккаунтом.')).toBeVisible()
})

test('installable assets exist and offline worker contains no private data', async ({ page, context }) => {
  await fresh(page)
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await page.reload()
  const manifest = await (await page.request.get('/manifest.webmanifest')).json()
  expect(manifest.display).toBe('standalone')
  for (const icon of manifest.icons) expect((await page.request.get(icon.src)).headers()['content-type']).toContain('image/png')
  const cached = await page.evaluate(async () => Promise.all((await caches.keys()).map(async name => ({ name, urls: (await (await caches.open(name)).keys()).map(r => r.url) }))))
  expect(cached.length).toBeGreaterThan(0)
  expect(cached.flatMap(c => c.urls)).toEqual(['http://127.0.0.1:4173/offline.html'])
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Продолжим, когда появится связь' })).toBeVisible()
  await expect(page.getByText(email)).toHaveCount(0)
  await context.setOffline(false)
  await page.getByRole('link', { name: 'Попробовать подключиться' }).click()
  await expect(page.getByRole('heading', { name: 'Что изучим сегодня?' })).toBeVisible()
})

test('keyboard can submit login and reach the main-content skip link', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Электронная почта').focus()
  await page.keyboard.type(email)
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Пароль', { exact: true })).toBeFocused()
  await page.keyboard.type(password)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Ваш прогресс — с вами' })).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Перейти к содержимому' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()
})
