-- PostgreSQL storage v1: UTC text and integer flags preserve the SQLite contract.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT UNIQUE,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    reading_mode TEXT NOT NULL DEFAULT 'normal',
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id TEXT NOT NULL UNIQUE,
    category_id BIGINT NOT NULL,
    source_ref TEXT,
    difficulty TEXT NOT NULL DEFAULT 'easy',
    status TEXT NOT NULL DEFAULT 'approved',
    question_text TEXT NOT NULL,
    explanation TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    option_index BIGINT NOT NULL,
    option_text TEXT NOT NULL,
    is_correct BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (question_id, option_index),
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE quiz_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT,
    difficulty_mode TEXT,
    started_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    finished_at TEXT,
    score BIGINT NOT NULL DEFAULT 0,
    total_questions BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'in_progress',
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE quiz_session_selected_categories (
    session_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (session_id, category_id),
    FOREIGN KEY (session_id) REFERENCES quiz_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE quiz_session_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    order_index BIGINT NOT NULL,
    content_snapshot TEXT,
    content_sha256 TEXT,
    snapshot_provenance TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (session_id, question_id),
    UNIQUE (session_id, order_index),
    FOREIGN KEY (session_id) REFERENCES quiz_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE quiz_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option_index BIGINT,
    is_correct BIGINT NOT NULL DEFAULT 0,
    answered_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (session_id, question_id),
    FOREIGN KEY (session_id) REFERENCES quiz_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE user_literature_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    literature_id TEXT NOT NULL CHECK (length(trim(literature_id)) > 0),
    reading_status TEXT NOT NULL CHECK (
        reading_status IN ('not_started', 'in_progress', 'read', 'revisit', 'skipped')
    ),
    progress_percent BIGINT CHECK (
        progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)
    ),
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT NOT NULL,
    last_opened_at TEXT,
    private_note TEXT,
    remind_at TEXT,
    UNIQUE (user_id, literature_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_quiz_sessions_user_status
    ON quiz_sessions(user_id, status);
CREATE INDEX idx_quiz_answers_session_question
    ON quiz_answers(session_id, question_id);
CREATE INDEX idx_quiz_session_questions_session_order
    ON quiz_session_questions(session_id, order_index);
CREATE INDEX idx_quiz_session_questions_question
    ON quiz_session_questions(question_id);
CREATE INDEX idx_user_literature_progress_user_id
    ON user_literature_progress(user_id);
CREATE INDEX idx_user_literature_progress_reading_status
    ON user_literature_progress(reading_status);
CREATE INDEX idx_user_literature_progress_user_updated
    ON user_literature_progress(user_id, updated_at);

CREATE TABLE web_accounts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        user_id BIGINT UNIQUE REFERENCES users(id),
        enabled BIGINT NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),
        verified_at BIGINT NOT NULL,
        created_at BIGINT NOT NULL
    );
CREATE TABLE web_sessions (
        digest TEXT PRIMARY KEY,
        account_id BIGINT NOT NULL REFERENCES web_accounts(id) ON DELETE CASCADE,
        created_at BIGINT NOT NULL,
        expires_at BIGINT NOT NULL,
        last_seen_at BIGINT NOT NULL
    );
CREATE TABLE web_mail_tokens (
        digest TEXT PRIMARY KEY,
        email TEXT NOT NULL,
        purpose TEXT NOT NULL CHECK(purpose IN ('register','recover')),
        account_id BIGINT REFERENCES web_accounts(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
    );
CREATE TABLE web_link_tokens (
        digest TEXT PRIMARY KEY,
        account_id BIGINT NOT NULL REFERENCES web_accounts(id) ON DELETE CASCADE,
        session_digest TEXT NOT NULL UNIQUE REFERENCES web_sessions(digest) ON DELETE CASCADE,
        proposed_user_id BIGINT REFERENCES users(id),
        telegram_confirmed BIGINT NOT NULL DEFAULT 0 CHECK(telegram_confirmed IN (0,1)),
        expires_at BIGINT NOT NULL
    );
CREATE TABLE web_auth_limits (
        bucket TEXT PRIMARY KEY, started_at BIGINT NOT NULL, count BIGINT NOT NULL
    );
CREATE INDEX idx_web_sessions_account ON web_sessions(account_id);
CREATE INDEX idx_web_mail_account ON web_mail_tokens(account_id);
CREATE INDEX idx_web_link_account ON web_link_tokens(account_id);
CREATE TABLE schema_migrations(version TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'));

CREATE FUNCTION guard_attempt_content() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.content_snapshot IS NOT NULL AND (
        NEW.content_snapshot IS DISTINCT FROM OLD.content_snapshot OR
        NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256 OR
        NEW.snapshot_provenance IS DISTINCT FROM OLD.snapshot_provenance OR
        NEW.session_id IS DISTINCT FROM OLD.session_id OR
        NEW.question_id IS DISTINCT FROM OLD.question_id
    ) THEN
        RAISE EXCEPTION 'Attempt content is immutable' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER immutable_attempt_content
BEFORE UPDATE OF content_snapshot,content_sha256,snapshot_provenance,session_id,question_id
ON quiz_session_questions FOR EACH ROW EXECUTE FUNCTION guard_attempt_content();

CREATE TABLE postgres_storage (
    singleton BIGINT PRIMARY KEY CHECK(singleton=1),
    version TEXT NOT NULL,
    ddl_sha256 TEXT NOT NULL,
    catalog_sha256 TEXT NOT NULL,
    import_manifest TEXT
);
